<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Mathjax-custom-macros" data-toc-modified-id="Mathjax-custom-macros-1" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Mathjax custom macros</a></span></li><li><span><a href="#Majorana-Fermions-With-QuTiP" data-toc-modified-id="Majorana-Fermions-With-QuTiP-2" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2&nbsp;&nbsp;</span>Majorana Fermions With QuTiP</a></span><ul class="toc-item"><li><span><a href="#Fermion-Ladder-Operators" data-toc-modified-id="Fermion-Ladder-Operators-2.1" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Fermion Ladder Operators</a></span></li><li><span><a href="#Construct-Majoranas-Using-Jordan-Wigner" data-toc-modified-id="Construct-Majoranas-Using-Jordan-Wigner-2.2" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Construct Majoranas Using Jordan-Wigner</a></span></li><li><span><a href="#Construct-Majorana-From-Fermions" data-toc-modified-id="Construct-Majorana-From-Fermions-2.3" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Construct Majorana From Fermions</a></span></li><li><span><a href="#Reconstruct-Fermion-From-Majorana" data-toc-modified-id="Reconstruct-Fermion-From-Majorana-2.4" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Reconstruct Fermion From Majorana</a></span></li><li><span><a href="#Collection-of-Majoranas" data-toc-modified-id="Collection-of-Majoranas-2.5" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Collection of Majoranas</a></span></li><li><span><a href="#Kitaev's-Construction" data-toc-modified-id="Kitaev's-Construction-2.6" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.6&nbsp;&nbsp;</span>Kitaev's Construction</a></span></li></ul></li></ul></div>

# Mathjax custom macros

$ \newcommand{\opexpect}[3]{\langle #1 \vert #2 \vert #3 \rangle} $
$ \newcommand{\rarrow}{\rightarrow} $
$ \newcommand{\bra}{\langle} $
$ \newcommand{\ket}{\rangle} $

$ \newcommand{\up}{\uparrow} $
$ \newcommand{\down}{\downarrow} $

$ \newcommand{\mb}[1]{\mathbf{#1}} $
$ \newcommand{\mc}[1]{\mathcal{#1}} $
$ \newcommand{\mbb}[1]{\mathbb{#1}} $
$ \newcommand{\mf}[1]{\mathfrak{#1}} $

$ \newcommand{\vect}[1]{\boldsymbol{\mathrm{#1}}} $
$ \newcommand{\expect}[1]{\langle #1\rangle} $

$ \newcommand{\innerp}[2]{\langle #1 \vert #2 \rangle} $
$ \newcommand{\fullbra}[1]{\langle #1 \vert} $
$ \newcommand{\fullket}[1]{\vert #1 \rangle} $
$ \newcommand{\supersc}[1]{^{\text{#1}}} $
$ \newcommand{\subsc}[1]{_{\text{#1}}} $
$ \newcommand{\sltwoc}{SL(2,\mathbb{C})} $
$ \newcommand{\sltwoz}{SL(2,\mathbb{Z})} $

$ \newcommand{\utilde}[1]{\underset{\sim}{#1}} $

In [1]:
import matplotlib
matplotlib.use('qt4agg')
%matplotlib inline

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from qutip import *

In [11]:
from hubbard import *

# Majorana Fermions With QuTiP

## Fermion Ladder Operators

In [5]:
a = destroy(2)

In [6]:
adag = create(2)

In [7]:
commutator(a,adag)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [13]:
a*adag + adag*a

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

In [ ]:
adag**2

In [ ]:
a, adag

In [ ]:
a + adag

In [17]:
sigmaz?

In [18]:
jordanWignerDestroyI(0,2)

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

## Construct Majoranas Using Jordan-Wigner

The function `jordanWignerDestroyI(k,N)` will return a fermionic operator acting on the k^th^ site on N site spin 1/2 system.

In [19]:
majoranaOps = []

In [20]:
N = 5

In [21]:
majoranaOps = [jordanWignerDestroyI(k,N) for k in range(N)]

In [22]:
majoranaOps[0]

Quantum object: dims = [[2, 2, 2, 2, 2], [2, 2, 2, 2, 2]], shape = (32, 32), type = oper, isherm = False
Qobj data =
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [29]:
identity([2]*5)

Quantum object: dims = [[2, 2, 2, 2, 2], [2, 2, 2, 2, 2]], shape = (32, 32), type = oper, isherm = True
Qobj data =
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]

In [32]:
m1 = majoranaOps[0]

In [ ]:
m1.da

In [36]:
for j in range(N):
    
#     print(majoranaOps[j])
    
    for k in range(N):
        
        print(j,k)
        
        m_jk = majoranaOps[j]*majoranaOps[k].dag() + majoranaOps[k].dag()*majoranaOps[j]

        #         print(isequal(m_jk, identity([2]*5)))
        
        print(isequal(m_jk, zeroOpN(5)))

0 0
False
0 1
True
0 2
True
0 3
True
0 4
True
1 0
True
1 1
False
1 2
True
1 3
True
1 4
True
2 0
True
2 1
True
2 2
False
2 3
True
2 4
True
3 0
True
3 1
True
3 2
True
3 3
False
3 4
True
4 0
True
4 1
True
4 2
True
4 3
True
4 4
False


In [39]:
spin_Jx(1)

Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
Qobj data =
[[0.         0.70710678 0.        ]
 [0.70710678 0.         0.70710678]
 [0.         0.70710678 0.        ]]

In [43]:
isinstance(0.1,int)

False

In [44]:
spin_Jz(0.5)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 0.5  0. ]
 [ 0.  -0.5]]

In [47]:
ket([0], dim=3)

Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]]

In [48]:
ket([1], dim=3)

Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]]

## Construct Majorana From Fermions

Given a fermionic operator $\psi$ one can construct two majoranas from it:
\begin{align}
    x & = \psi + \psi^\dagger \nonumber \\
    y & = -i(\psi - \psi^\dagger)
\end{align}

In [ ]:
maj1 = a + adag
maj1

We can check that the majorana operator satisfies:
$$ x^2 = 1 $$
i.e. the majorana is its own anti-particle

In [ ]:
maj1**2

In [ ]:
maj2 = (a - adag)/1j

In [ ]:
maj2

In [ ]:
maj2**2

Check that two Majoranas anticommute:
$$ \{ x, y \} = 0 $$

In [ ]:
def anticommutator(X,Y):
    return commutator(X,Y,kind='anti')

In [ ]:
anticommutator(maj1,maj2)

## Reconstruct Fermion From Majorana

Given two majoranas $x, y$, one can construct a single fermionic operator $\psi$ from these:
\begin{align}
    \psi & = (x + iy)/2 \nonumber \\
    \psi^\dagger & = (x - iy)/2
\end{align}

## Collection of Majoranas

In [ ]:
posOperatorN?

In [ ]:
n = 2

In [ ]:
majoranas = [posOperatorN(maj1, i = k, N = n) for k in range(n)]

In [ ]:
majoranas

In [ ]:
anticommutator(majoranas[0],majoranas[4])

In [ ]:
zero_ket(32,dims=[[2, 2, 2, 2, 2], [2, 2, 2, 2, 2]])

In [ ]:
def zero_operatorN(N=2):
    zeroket = qutip.zero_ket(2**N,dims=[[2]*N,[2]*N])
    return zeroket * zeroket.dag()

In [ ]:
zero_operatorN(5)

In [ ]:
isequal(anticommutator(majoranas[0],majoranas[4]),zero_operatorN(5))

In [ ]:
isequal(majoranas[0]**2,idOp)

In [ ]:
commutator(majoranas[0],majoranas[4]) == zero_operatorN(5)

In [ ]:
idOp = tensor(identityList(N=n))

In [ ]:
braidops = [(idOp + majoranas[k+1]*majoranas[k])/np.sqrt(2) for k in range(n-1)]

In [ ]:
braidopsinverse = [(idOp - majoranas[k+1]*majoranas[k])/np.sqrt(2) for k in range(n-1)]

In [ ]:
braidops[0]*braidops[0]

In [ ]:
idOp

In [ ]:
qutip.isequal?

In [ ]:
majoranas2 = [tensor([*[identity(2)]*k,maj1,*[identity(2)]*(5-k-1)]) for k in range(5)]

In [ ]:
majoranas2

In [ ]:
isequal(anticommutator(majoranas2[0],majoranas2[4]), zero_operatorN(5))

In [ ]:
[*[maj1]*3,identity(2)]

**Conclusion:** Implement Majoranas using formalism in Kitaev2008Anyons paper, Sec 4.1 onwards.

## Kitaev's Construction

Consider a system with $n$ fermionic operators: $ a_k, a^\dagger_k; k \in \{1,\ldots,n\} $. From these fermionic operators we can construct $2n$ Majorana spinors:
$$ c_{2k} = -i ( a_k - a^\dagger_k); \quad c_{2k-1} = a_k + a^\dagger_k $$
One can check that these operators satisfy the following relations:
\begin{align}
    c_j = c^\dagger_j \quad & \text{hermitian} \nonumber \\
    c^2_j = 1 \quad & \text{root of identity} \nonumber \\
    \{c_j, c_l \} = 0; \text{if} j\ne l ; \quad & \text{anticommuting}
\end{align}


In [ ]:
# Specify number of fermionic operators:

N = 5

# Generate array of fermionic creation and annihilation operators for N site system

createOps = []
destroyOps = []

createOps = [posOperatorN(create(2), k, N) for k in range(N)]
destroyOps = [posOperatorN(destroy(2), k, N) for k in range(N)]

In [ ]:
def majoranaOps(N = 1, dims = 2):
    '''Creates 2N Majorana operators using Kitaev's construction
    '''
    
    # Generate array of fermionic creation and annihilation operators for N site system

    createOps = []
    destroyOps = []

    createOps = [posOperatorN(create(2), k, N) for k in range(N)]
    destroyOps = [posOperatorN(destroy(2), k, N) for k in range(N)]    

    majoranas = []
    
    for k in range(N):
        majoranas.append((1j)*(destroyOps[k] - createOps[k]))
        majoranas.append(destroyOps[k] + createOps[k])
        
    return majoranas
    

In [ ]:
majoranas = majoranaOps()

In [ ]:
for i in majoranas:
    print(i**2)

In [ ]:
qtAntiCommutator(majoranas[0], majoranas[1])

In [ ]:
majoranas4 = majoranaOps(N = 2)

In [ ]:
majoranas4[1]

In [ ]:
for i in majoranas4:
    print(i**2)

In [ ]:
for i in range(len(majoranas4)):
    
    print(isherm(majoranas4[i]))
    
    for j in range(i+1, len(majoranas4)):
        print(i,j)
        
        print(qtAntiCommutator(majoranas4[i],majoranas4[j]))

In [ ]:
for k in range(N):
    majoranaOps.append((1j)*(destroyOps[k] - createOps[k]))
    majoranaOps.append(destroyOps[k] + createOps[k])

In [ ]:
len(majoranaOps)

In [ ]:
identityOp = identity([2]*N)

In [ ]:
majoranaOps[5]**2 == identityOp

In [ ]:
for j in range(2*N):
    for k in range(j+1,2*N):
        print(j,k)
        print(anticommutator(majoranaOps[j],majoranaOps[k]) == zero_operatorN(5))

In [ ]:
identity([2]*5)

In [ ]:
np.allclose(anticommutator(majoranaOps[0].full(), majoranaOps[1].full()).full(), np.zeros([32,32]))

In [ ]:
anticommutator(majoranaOps[0].full(), majoranaOps[1].full())

In [ ]:
commutator?

In [ ]:
def qtAntiCommutator(X,Y):
    if type(X) == Qobj and type(Y) == Qobj:
        if len(X.shape) == 2 and len(Y.shape) == 2:
            if X.shape[1] == Y.shape[0]:
                return qutip.commutator(X,Y,kind='anti')
            else:
                raise ValueError("Number of columns of first argument must be equal to number of rows of second argument")
        else:
            raise ValueError("Arguements must be QuTiP arrays of shape M x N")
    else:
        raise ValueError("Arguments must be QuTiP arrays of compatible dimensions")

In [ ]:
maj1.shape

In [ ]:
qtAntiCommutator(maj1,maj2)

In [ ]:
def npAntiCommutator(X,Y):
    if type(X) == np.ndarray and type(Y) == np.ndarray:
        if len(X.shape) == 2 and len(Y.shape) == 2:
            if X.shape[1] == Y.shape[0]:
                return X*Y + Y*X
            else:
                raise ValueError("Number of columns of first argument must be equal to number of rows of second argument")
        else:
            raise ValueError("Arguements must be numpy arrays of shape M x N")
    else:
        raise ValueError("Arguments must be numpy arrays of compatible dimensions")

In [ ]:
npAntiCommutator(maj1.full(),maj2.full())

In [ ]:
type(maj2.full())

In [ ]:
arr = maj2.full()
arr

In [ ]:
arr.shape

In [ ]:
type(maj1)

In [ ]:
maj1.__class__

In [ ]:
majoranaOps = []

In [ ]:
majoranaOps.append((-1j)*(destroy(2) - create(2)))
majoranaOps.append((destroy(2) + create(2)))

In [ ]:
majoranaOps

In [ ]:
for i in majoranaOps:
    print(i**2)

In [ ]:
qtAntiCommutator(majoranaOps[0],majoranaOps[1])