<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Mathjax-custom-macros" data-toc-modified-id="Mathjax-custom-macros-1" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Mathjax custom macros</a></span></li><li><span><a href="#Majorana-Fermions-With-QuTiP" data-toc-modified-id="Majorana-Fermions-With-QuTiP-2" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2&nbsp;&nbsp;</span>Majorana Fermions With QuTiP</a></span><ul class="toc-item"><li><span><a href="#Fermion-Ladder-Operators" data-toc-modified-id="Fermion-Ladder-Operators-2.1" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Fermion Ladder Operators</a></span></li><li><span><a href="#Construct-Majorana-From-Fermions" data-toc-modified-id="Construct-Majorana-From-Fermions-2.2" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Construct Majorana From Fermions</a></span></li><li><span><a href="#Reconstruct-Fermion-From-Majorana" data-toc-modified-id="Reconstruct-Fermion-From-Majorana-2.3" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Reconstruct Fermion From Majorana</a></span></li><li><span><a href="#Collection-of-Majoranas" data-toc-modified-id="Collection-of-Majoranas-2.4" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Collection of Majoranas</a></span></li><li><span><a href="#Kitaev's-Construction" data-toc-modified-id="Kitaev's-Construction-2.5" data-vivaldi-spatnav-clickable="1"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Kitaev's Construction</a></span></li></ul></li></ul></div>

# Mathjax custom macros

$ \newcommand{\opexpect}[3]{\langle #1 \vert #2 \vert #3 \rangle} $
$ \newcommand{\rarrow}{\rightarrow} $
$ \newcommand{\bra}{\langle} $
$ \newcommand{\ket}{\rangle} $

$ \newcommand{\up}{\uparrow} $
$ \newcommand{\down}{\downarrow} $

$ \newcommand{\mb}[1]{\mathbf{#1}} $
$ \newcommand{\mc}[1]{\mathcal{#1}} $
$ \newcommand{\mbb}[1]{\mathbb{#1}} $
$ \newcommand{\mf}[1]{\mathfrak{#1}} $

$ \newcommand{\vect}[1]{\boldsymbol{\mathrm{#1}}} $
$ \newcommand{\expect}[1]{\langle #1\rangle} $

$ \newcommand{\innerp}[2]{\langle #1 \vert #2 \rangle} $
$ \newcommand{\fullbra}[1]{\langle #1 \vert} $
$ \newcommand{\fullket}[1]{\vert #1 \rangle} $
$ \newcommand{\supersc}[1]{^{\text{#1}}} $
$ \newcommand{\subsc}[1]{_{\text{#1}}} $
$ \newcommand{\sltwoc}{SL(2,\mathbb{C})} $
$ \newcommand{\sltwoz}{SL(2,\mathbb{Z})} $

$ \newcommand{\utilde}[1]{\underset{\sim}{#1}} $

In [246]:
import matplotlib
matplotlib.use('qt4agg')
%matplotlib inline

In [247]:
import numpy as np
import matplotlib.pyplot as plt
from qutip import *

In [248]:
from hubbard import *

# Majorana Fermions With QuTiP

## Fermion Ladder Operators

In [249]:
a = destroy(2)

In [250]:
adag = create(2)

In [251]:
commutator(a,adag)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [252]:
anticommutator(a,adag)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

In [13]:
adag**2

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 0.]
 [0. 0.]]

In [20]:
a, adag

(Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
 Qobj data =
 [[0. 1.]
  [0. 0.]],
 Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
 Qobj data =
 [[0. 0.]
  [1. 0.]])

In [21]:
a + adag

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 1.]
 [1. 0.]]

## Construct Majorana From Fermions

Given a fermionic operator $\psi$ one can construct two majoranas from it:
\begin{align}
    x & = \psi + \psi^\dagger \nonumber \\
    y & = -i(\psi - \psi^\dagger)
\end{align}

In [22]:
maj1 = a + adag
maj1

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 1.]
 [1. 0.]]

We can check that the majorana operator satisfies:
$$ x^2 = 1 $$
i.e. the majorana is its own anti-particle

In [23]:
maj1**2

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

In [24]:
maj2 = (a - adag)/1j

In [25]:
maj2

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]

In [26]:
maj2**2

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

Check that two Majoranas anticommute:
$$ \{ x, y \} = 0 $$

In [27]:
def anticommutator(X,Y):
    return commutator(X,Y,kind='anti')

In [28]:
anticommutator(maj1,maj2)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 0.]
 [0. 0.]]

## Reconstruct Fermion From Majorana

Given two majoranas $x, y$, one can construct a single fermionic operator $\psi$ from these:
\begin{align}
    \psi & = (x + iy)/2 \nonumber \\
    \psi^\dagger & = (x - iy)/2
\end{align}

## Collection of Majoranas

In [31]:
posOperatorN?

In [103]:
n = 2

In [104]:
majoranas = [posOperatorN(maj1, i = k, N = n) for k in range(n)]

In [106]:
majoranas

[Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
 Qobj data =
 [[0. 0. 1. 0.]
  [0. 0. 0. 1.]
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]],
 Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
 Qobj data =
 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]]]

In [50]:
anticommutator(majoranas[0],majoranas[4])

Quantum object: dims = [[2, 2, 2, 2, 2], [2, 2, 2, 2, 2]], shape = (32, 32), type = oper, isherm = True
Qobj data =
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [66]:
zero_ket(32,dims=[[2, 2, 2, 2, 2], [2, 2, 2, 2, 2]])

Quantum object: dims = [[2, 2, 2, 2, 2], [2, 2, 2, 2, 2]], shape = (32, 1), type = oper, isherm = False
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [74]:
def zero_operatorN(N=2):
    zeroket = qutip.zero_ket(2**N,dims=[[2]*N,[2]*N])
    return zeroket * zeroket.dag()

In [96]:
zero_operatorN(5)

Quantum object: dims = [[2, 2, 2, 2, 2], [2, 2, 2, 2, 2]], shape = (32, 32), type = oper, isherm = True
Qobj data =
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [100]:
isequal(anticommutator(majoranas[0],majoranas[4]),zero_operatorN(5))

False

In [102]:
isequal(majoranas[0]**2,idOp)

True

In [82]:
commutator(majoranas[0],majoranas[4]) == zero_operatorN(5)

True

In [89]:
idOp = tensor(identityList(N=n))

In [90]:
braidops = [(idOp + majoranas[k+1]*majoranas[k])/np.sqrt(2) for k in range(n-1)]

In [91]:
braidopsinverse = [(idOp - majoranas[k+1]*majoranas[k])/np.sqrt(2) for k in range(n-1)]

In [95]:
braidops[0]*braidops[0]

Quantum object: dims = [[2, 2, 2, 2, 2], [2, 2, 2, 2, 2]], shape = (32, 32), type = oper, isherm = True
Qobj data =
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]

In [94]:
idOp

Quantum object: dims = [[2, 2, 2, 2, 2], [2, 2, 2, 2, 2]], shape = (32, 32), type = oper, isherm = True
Qobj data =
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]

In [99]:
qutip.isequal?

In [127]:
majoranas2 = [tensor([*[identity(2)]*k,maj1,*[identity(2)]*(5-k-1)]) for k in range(5)]

In [128]:
majoranas2

[Quantum object: dims = [[2, 2, 2, 2, 2], [2, 2, 2, 2, 2]], shape = (32, 32), type = oper, isherm = True
 Qobj data =
 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]],
 Quantum object: dims = [[2, 2, 2, 2, 2], [2, 2, 2, 2, 2]], shape = (32, 32), type = oper, isherm = True
 Qobj data =
 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]],
 Quantum object: dims = [[2, 2, 2, 2, 2], [2, 2, 2, 2, 2]], shape = (32, 32), type = oper, isherm = True
 Qobj data =
 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]],
 Quantum object: dims = [[2, 2, 2, 2, 2], [2, 2, 2, 2, 2]], shape = (32, 32), type = oper, isherm = True
 Qobj data =
 [[0. 0. 1. ... 0. 0. 0.]
  [0. 0. 0

In [134]:
isequal(anticommutator(majoranas2[0],majoranas2[4]), zero_operatorN(5))

False

In [118]:
[*[maj1]*3,identity(2)]

[Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
 Qobj data =
 [[0. 1.]
  [1. 0.]],
 Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
 Qobj data =
 [[0. 1.]
  [1. 0.]],
 Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
 Qobj data =
 [[0. 1.]
  [1. 0.]],
 Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
 Qobj data =
 [[1. 0.]
  [0. 1.]]]

**Conclusion:** Implement Majoranas using formalism in Kitaev2008Anyons paper, Sec 4.1 onwards.

## Kitaev's Construction

Consider a system with $n$ fermionic operators: $ a_k, a^\dagger_k; k \in \{1,\ldots,n\} $. From these fermionic operators we can construct $2n$ Majorana spinors:
$$ c_{2k} = -i ( a_k - a^\dagger_k); \quad c_{2k-1} = a_k + a^\dagger_k $$
One can check that these operators satisfy the following relations:
\begin{align}
    c_j = c^\dagger_j \quad & \text{hermitian} \nonumber \\
    c^2_j = 1 \quad & \text{root of identity} \nonumber \\
    \{c_j, c_l \} = 0; \text{if} j\ne l ; \quad & \text{anticommuting}
\end{align}


In [253]:
# Specify number of fermionic operators:

N = 5

# Generate array of fermionic creation and annihilation operators for N site system

createOps = []
destroyOps = []

createOps = [posOperatorN(create(2), k, N) for k in range(N)]
destroyOps = [posOperatorN(destroy(2), k, N) for k in range(N)]

In [254]:
def majoranaOps(N = 1, dims = 2):
    '''Creates 2N Majorana operators using Kitaev's construction
    '''
    
    # Generate array of fermionic creation and annihilation operators for N site system

    createOps = []
    destroyOps = []

    createOps = [posOperatorN(create(2), k, N) for k in range(N)]
    destroyOps = [posOperatorN(destroy(2), k, N) for k in range(N)]    

    majoranas = []
    
    for k in range(N):
        majoranas.append((1j)*(destroyOps[k] - createOps[k]))
        majoranas.append(destroyOps[k] + createOps[k])
        
    return majoranas
    

In [255]:
majoranas = majoranaOps()

In [256]:
for i in majoranas:
    print(i**2)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]


In [257]:
qtAntiCommutator(majoranas[0], majoranas[1])

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 0.]
 [0. 0.]]

In [258]:
majoranas4 = majoranaOps(N = 2)

In [265]:
majoranas4[1]

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]

In [243]:
for i in majoranas4:
    print(i**2)

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [266]:
for i in range(len(majoranas4)):
    
    print(isherm(majoranas4[i]))
    
    for j in range(i+1, len(majoranas4)):
        print(i,j)
        
        print(qtAntiCommutator(majoranas4[i],majoranas4[j]))

True
0 1
Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
0 2
Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.  0.  0. -2.]
 [ 0.  0.  2.  0.]
 [ 0.  2.  0.  0.]
 [-2.  0.  0.  0.]]
0 3
Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.+0.j 0.+0.j 0.+2.j]
 [0.+0.j 0.+0.j 0.+2.j 0.+0.j]
 [0.+0.j 0.-2.j 0.+0.j 0.+0.j]
 [0.-2.j 0.+0.j 0.+0.j 0.+0.j]]
True
1 2
Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.+0.j 0.+0.j 0.+2.j]
 [0.+0.j 0.+0.j 0.-2.j 0.+0.j]
 [0.+0.j 0.+2.j 0.+0.j 0.+0.j]
 [0.-2.j 0.+0.j 0.+0.j 0.+0.j]]
1 3
Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 2.]
 [0. 0. 2. 0.]
 [0. 2. 0. 0.]
 [2. 0. 0. 0.]]
True
2 3
Quantum object: dims = [[2, 2], 

In [174]:
for k in range(N):
    majoranaOps.append((1j)*(destroyOps[k] - createOps[k]))
    majoranaOps.append(destroyOps[k] + createOps[k])

In [175]:
len(majoranaOps)

10

In [180]:
identityOp = identity([2]*N)

In [183]:
majoranaOps[5]**2 == identityOp

True

In [190]:
for j in range(2*N):
    for k in range(j+1,2*N):
        print(j,k)
        print(anticommutator(majoranaOps[j],majoranaOps[k]) == zero_operatorN(5))

0 1
True
0 2
False
0 3
False
0 4
False
0 5
False
0 6
False
0 7
False
0 8
False
0 9
False
1 2
False
1 3
False
1 4
False
1 5
False
1 6
False
1 7
False
1 8
False
1 9
False
2 3
True
2 4
False
2 5
False
2 6
False
2 7
False
2 8
False
2 9
False
3 4
False
3 5
False
3 6
False
3 7
False
3 8
False
3 9
False
4 5
True
4 6
False
4 7
False
4 8
False
4 9
False
5 6
False
5 7
False
5 8
False
5 9
False
6 7
True
6 8
False
6 9
False
7 8
False
7 9
False
8 9
True


In [179]:
identity([2]*5)

Quantum object: dims = [[2, 2, 2, 2, 2], [2, 2, 2, 2, 2]], shape = (32, 32), type = oper, isherm = True
Qobj data =
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]

In [198]:
np.allclose(anticommutator(majoranaOps[0].full(), majoranaOps[1].full()).full(), np.zeros([32,32]))

AttributeError: 'numpy.ndarray' object has no attribute 'full'

In [197]:
anticommutator(majoranaOps[0].full(), majoranaOps[1].full())

array([[0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       ...,
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j]])

In [199]:
commutator?

In [218]:
def qtAntiCommutator(X,Y):
    if type(X) == Qobj and type(Y) == Qobj:
        if len(X.shape) == 2 and len(Y.shape) == 2:
            if X.shape[1] == Y.shape[0]:
                return qutip.commutator(X,Y,kind='anti')
            else:
                raise ValueError("Number of columns of first argument must be equal to number of rows of second argument")
        else:
            raise ValueError("Arguements must be QuTiP arrays of shape M x N")
    else:
        raise ValueError("Arguments must be QuTiP arrays of compatible dimensions")

In [217]:
maj1.shape

(2, 2)

In [220]:
qtAntiCommutator(maj1,maj2)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 0.]
 [0. 0.]]

In [228]:
def npAntiCommutator(X,Y):
    if type(X) == np.ndarray and type(Y) == np.ndarray:
        if len(X.shape) == 2 and len(Y.shape) == 2:
            if X.shape[1] == Y.shape[0]:
                return X*Y + Y*X
            else:
                raise ValueError("Number of columns of first argument must be equal to number of rows of second argument")
        else:
            raise ValueError("Arguements must be numpy arrays of shape M x N")
    else:
        raise ValueError("Arguments must be numpy arrays of compatible dimensions")

In [227]:
npAntiCommutator(maj1.full(),maj2.full())

array([[0.+0.j, 0.-2.j],
       [0.+2.j, 0.+0.j]])

In [210]:
type(maj2.full())

numpy.ndarray

In [221]:
arr = maj2.full()
arr

array([[0.+0.j, 0.-1.j],
       [0.+1.j, 0.+0.j]])

In [222]:
arr.shape

(2, 2)

In [204]:
type(maj1)

qutip.qobj.Qobj

In [207]:
maj1.__class__

qutip.qobj.Qobj

In [229]:
majoranaOps = []

In [231]:
majoranaOps.append((-1j)*(destroy(2) - create(2)))
majoranaOps.append((destroy(2) + create(2)))

In [232]:
majoranaOps

[Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
 Qobj data =
 [[0.+0.j 0.-1.j]
  [0.+1.j 0.+0.j]],
 Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
 Qobj data =
 [[0. 1.]
  [1. 0.]]]

In [234]:
for i in majoranaOps:
    print(i**2)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]


In [235]:
qtAntiCommutator(majoranaOps[0],majoranaOps[1])

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 0.]
 [0. 0.]]