In [1]:
import random
import array
import numpy as np

In [2]:
chainN = 100 # number of qubits in chain
tempT = 273 # temperature of system in degrees Kelvin

In [3]:
coef_ij = np.zeros((chainN,chainN)) # spin-spin coupling coefficients

In [4]:
def randInput(n):
    ''' Generates random string of length n, containing 0s and 1s '''
    output = []
    for i in range(n):
        output.append(random.randint(0,1))
    return output

In [87]:
def zeroCoefs(coefs):
    ''' Takes chainN * chainN size matrix as input & sets all values to zero '''
    try:
        coefs = np.zeros((chainN,chainN))
        return coefs
    except Exception:
        return false

def identityCoefs(coefs):
    ''' Takes chainN * chainN size matrix as input & sets diagonals to one, all other entries to zero '''
    try:
        # use np.diagflat method to create diagonal array
        # use list comprehension to generate list of 1s to pass to np.diagflat
        coefs = np.diagflat([1 for i in range(chainN)])
        return coefs
    except Exception:
        return false
    
def randCoefs(N, max_val = 1.0, min_val = -1.0, symmetric = True):
    ''' Creates N * N size matrix and randomly initializes all entries to a value between
    max_val and min_val. If not given, these default to 1.0 and -1.0 respectively. Unless specified
    using the variable symmetric=FALSE, the generated matrix will be symmetric'''
    try:
        coefs = np.zeros((N,N))
        delta = max_val - min_val
        
        if symmetric:
            for i in range(N):
                for j in range(0,i+1):
                    coefs[i][j] = max_val - delta * np.random.random_sample()
                    coefs[j][i] = coefs[i][j]
        else:
            for i in range(N):
                for j in range(N):
                    coefs[i][j] = max_val - delta * np.random.random_sample()
        return coefs
    except Exception:
        return false

def randVec(N, values=[0,1]):
    ''' Creates size N array with each element assigned a member of values[] array at random '''
    try:
        vect = np.zeros(N)
        lenval = len(values)
        for i in range(N):
            vect[i] = values[np.random.randint(0,lenval)]
        return vect
    except Exception:
        return false

In [90]:
randVec(10,[-1,1])

array([-1.,  1., -1., -1.,  1.,  1.,  1., -1.,  1., -1.])

In [29]:
chainN=4

In [39]:
coefs = np.zeros((chainN,chainN))
print coefs
print randCoefs(coefs,symmetric=False)
print randCoefs(coefs,symmetric=True)
randCoefs(coef_ij)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ -3.11022273e-01   1.56639062e-01   1.72331637e-01   6.08247297e-01]
 [  9.43739063e-04   8.39225820e-01  -4.73948128e-01  -2.33456618e-01]
 [  5.81457865e-01  -8.75221875e-01   8.41080597e-01  -9.48005311e-01]
 [  3.81057100e-01   8.33421011e-01  -6.15098166e-01   7.06132363e-02]]
[[-0.69490754 -0.94455312 -0.87923902 -0.96253261]
 [-0.94455312 -0.89355978 -0.60297668  0.40554619]
 [-0.87923902 -0.60297668  0.78956885  0.91044651]
 [-0.96253261  0.40554619  0.91044651 -0.42646465]]


array([[-0.95800242,  0.23756332, -0.19331752, -0.20895897],
       [ 0.23756332,  0.91401916, -0.97191911,  0.5149586 ],
       [-0.19331752, -0.97191911, -0.54723673, -0.67322553],
       [-0.20895897,  0.5149586 , -0.67322553,  0.16463271]])

In [57]:
def hamilton(inputVec,coefs):
    ''' Accepts 1d vector of length chainN and chainN * chainN matrix as input.
    Returns expectation value of Hamiltonian operator '''
#    n = len(inputVec)
    if np.shape(inputVec) != (chainN,):
        print "Vector length is not equal to: ", chainN
        return
    if np.shape(coefs) != (chainN,chainN):
        print "Coefficient matrix dimensions are not:", chainN, "x", chainN
    # ensure that val is initialized to float value by adding decimal
    val = 0.
    for i in range(chainN):
        for j in range(chainN):
           val = val + coefs[i][j]*inputVec[i]*inputVec[j]
    return val

In [69]:
print chainN
coefs = identityCoefs(coefs)
coefs

4


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [71]:
ivec = randInput(chainN)
print ivec

[0, 1, 1, 0]


In [73]:
hamilton(ivec,coefs)

2.0

In [75]:
chainN = 100
coefs = randCoefs(coefs, symmetric=True)
ivec = randInput(chainN)

In [77]:
hamilton(ivec,coefs)

-67.400087449821001

In [82]:
total = 0.
average = 0.
ntries = 100
random.Random()
for i in range(ntries):
    h = hamilton(randInput(chainN),coefs)
    total+= h
    print h,
average = total/ntries
print
print average, total

60.1167059772 -64.4021191507 -29.3086201031 -4.1351582183 -94.2011083378 62.1275207488 -61.8744079238 -18.1928573165 -74.2760647245 -28.4808513398 -3.32892207003 15.7130063729 -25.4322214284 -5.43991093506 -41.0702200353 -23.12690268 -67.1905649829 -5.13461010801 52.8813554165 -28.6840199149 -4.98087835384 19.066629303 -31.4217682113 -25.3265780146 24.7689851608 4.87157091413 -57.8325976631 -40.4800593494 -56.982282837 -64.0183515016 -46.0971498325 -26.4314671735 -101.091696893 -84.1140229375 -16.8174216846 -23.0274492099 -58.045506509 -31.9746924128 -16.8017044986 -38.9613113416 -62.7837888042 -6.75163602124 7.63274215971 14.6478847053 2.72663494922 25.0625669045 -44.0399983774 -116.285861427 17.2783024138 -92.6100024075 -6.04820032377 -58.8090922907 -3.4427050511 -9.85762440396 -34.531917404 -37.6792533915 -48.9066610046 13.8170013527 30.6268523915 -5.31216931152 -7.14112476267 2.99231087505 64.2853530284 -8.97615463286 10.1118131207 -21.9743037011 -24.6036964025 -103.949595872 50.70

In [92]:
-2. + 0.1 * range(10)

TypeError: can't multiply sequence by non-int of type 'float'

In [97]:
!git init

Initialized empty Git repository in /Users/deepak/root/code/ipython-notebooks/.git/


In [98]:
!git status

On branch master

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.ipynb_checkpoints/
	Nov 5, 2014, file-mgmt.ipynb
	Oct-11-2014, Plotting Complex Functions.ipynb
	Oct-13-2014, QM with QuTiP again.ipynb
	Oct-14-2014 1 dim spin system.ipynb
	PySide - interactive application programming.ipynb
	Sandbox.ipynb
	matplotlib-tilings.ipynb
	opencv-video-processing.ipynb
	planck_fullsky.jpg
	qcirc-0.png
	qcirc-1.png
	qcirc.pdf
	qcirc.png
	qcirc.tex
	qutip-notebooks/
	qutip-qm with python.ipynb
	simple.bmp
	spin-system-1d.ipynb
	static/
	sympy - symbolic python.ipynb

nothing added to commit but untracked files present (use "git add" to track)


In [99]:
!git add *.ipynb

In [100]:
!git commit -m "first commit. all ipy notebooks"

[master (root-commit) c4769d1] first commit. all ipy notebooks
 11 files changed, 4756 insertions(+)
 create mode 100755 Nov 5, 2014, file-mgmt.ipynb
 create mode 100755 Oct-11-2014, Plotting Complex Functions.ipynb
 create mode 100755 Oct-13-2014, QM with QuTiP again.ipynb
 create mode 100755 Oct-14-2014 1 dim spin system.ipynb
 create mode 100755 PySide - interactive application programming.ipynb
 create mode 100755 Sandbox.ipynb
 create mode 100755 matplotlib-tilings.ipynb
 create mode 100755 opencv-video-processing.ipynb
 create mode 100755 qutip-qm with python.ipynb
 create mode 100755 spin-system-1d.ipynb
 create mode 100755 sympy - symbolic python.ipynb


In [101]:
!cd qutip-notebooks/
!ls

Nov 5, 2014, file-mgmt.ipynb                       qcirc-1.png
Oct-11-2014, Plotting Complex Functions.ipynb      qcirc.pdf
Oct-13-2014, QM with QuTiP again.ipynb             qcirc.png
Oct-14-2014 1 dim spin system.ipynb                qcirc.tex
PySide - interactive application programming.ipynb qutip-notebooks
Sandbox.ipynb                                      qutip-qm with python.ipynb
matplotlib-tilings.ipynb                           simple.bmp
opencv-video-processing.ipynb                      spin-system-1d.ipynb
planck_fullsky.jpg                                 static
qcirc-0.png                                        sympy - symbolic python.ipynb


In [102]:
!cd qutip-notebooks

In [103]:
!pwd

/Users/deepak/root/code/ipython-notebooks


In [104]:
!lcd qutip-notebooks

/bin/sh: lcd: command not found
